/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.FileUploadAPI.sga.FileUploadAPI.Services;


public enum TransferType implements org.apache.thrift.TEnum {
  REQUEST(0),
  PROGRESS(1);

  private final int value;

  private TransferType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TransferType findByValue(int value) { 
    switch (value) {
      case 0:
        return REQUEST;
      case 1:
        return PROGRESS;
      default:
        return null;
    }
  }
}
